/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.tapad;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ExampleEnum { 
  FOO, BAR, BAZ  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ExampleEnum\",\"namespace\":\"com.tapad\",\"symbols\":[\"FOO\",\"BAR\",\"BAZ\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
